lista = [1, 2, 3]
print(lista)
lista.append(4)
print(lista) 
lista.extend([5, 6]) 
print(lista)
lista.insert(1, 99) 
print(lista)
lista.remove(99) 
print(lista)
eliminado = lista.pop(2) 
print(eliminado)
lista.clear() 
print(lista)
numeros = [3, 1, 4, 2]
print(numeros)
numeros.sort() 
print(numeros)
nueva_lista = sorted(numeros, reverse=True) 
print(nueva_lista)
posicion = numeros.index(3) 
print(posicion)
repeticiones = numeros.count(3) 
print(repeticiones)
numeros.reverse() 
print(numeros)
copia = numeros.copy()
print(copia)